---
title: "Tarea 2, Pedro Montenegro Masís"
output: 
  flexdashboard::flex_dashboard:
    self_contained: false
    vertical_layout: scroll
    theme: united
    highlight: kate
    colortheme: "dolphin"
    orientation: row
    df_print: paged
---

Row {data-high=15}
-----------------------------------------------------------------------
### **Visualización GIS África**
**Introducción:** El conjunto de datos World, considerando la información de África para visualizar la información del índice de desarrollo humano.


```{r message=FALSE, warning=FALSE}
library(sf)
library(sp)
library(spData)
library(tidyverse)
library(tmap)
library(mapview)
library(ggplot2)
library(ggspatial)
library(ggmap)
library(classInt)
library(spacetime)
library(cartography)
library(raster)
#library(spDataLarge)
library(leaflet)
```

**Información World selección África**

```{r include=FALSE}
africa <- world %>% 
  filter(continent == "Africa", !is.na(iso_a2)) %>% 
  left_join(worldbank_df, by = "iso_a2") %>% 
  dplyr::select(name, subregion, gdpPercap, HDI, pop_growth) %>% 
  st_transform("+proj=aea +lat_1=20 +lat_2=-23 +lat_0=0 +lon_0=25")

africa_sp <- as(africa$geom, 'Spatial')
#class(africa_sp)

```

```{r}
world %>% st_drop_geometry() %>% 
  group_by(continent) %>% summarise(puntos= n()) %>%
    knitr::kable("html",format.args = list(decimal.mark = ',', big.mark = ".")) %>%
    kableExtra::kable_styling(c("striped"), full_width = F, position = "center")  %>%  
    kableExtra::add_header_above(c("Visualización de datos World" = 2))
```


Row2 {data-width=200}
-----------------------------------------------------------------------

### **Gráfico  sf**

```{r  out.width='50%', fig.align='center'}
africa %>% 
  ggplot() +
  geom_sf(aes(geometry= geom, fill= HDI)) +  
  scale_fill_viridis_c(guide = guide_legend(title = "HDI")) +
  theme_minimal() + 
  ggtitle("Distribución del Índice de Desarrollo Humano",
         subtitle= "Africa")
```

Row3 {data-width=200}
-----------------------------------------------------------------------

### **Gráficos con tmap interactivo HDI, Africa 1**

```{r message=FALSE, warning=FALSE}
tmap_mode("view") 

tm_shape(africa)+
tm_polygons("HDI") +
    tm_fill(col = "África", title = "Distribución del índice de desarrollo humano")

tmap_mode("plot")
```

### **Gráficos con tmap interactivo HDI, Africa 2**

```{r}
tmap_mode("view")
tm_basemap("Stamen.Watercolor") +
tm_shape(africa) + tm_polygons("HDI", convert2density = TRUE) + tm_bubbles(size = "HDI", col = "red") +
tm_tiles("Stamen.TonerLabels")
```

Row4 {data-width=200}
-----------------------------------------------------------------------
### **Mapview interactivo HDI, Africa 1**

```{r}
m = mapview::mapview(africa)
m@map
```

Row5 {data-width=400}
-----------------------------------------------------------------------

### **Gráficos tmap regular, 1**

```{r message=FALSE, warning=FALSE}
tmap_mode("plot")

tm_shape(africa) + tm_polygons("HDI", convert2density = TRUE)+
  tm_bubbles(size = "HDI", col= "HDI") +
  tm_scale_bar(position=c("right", "bottom")) +
  tm_compass(type = "8star",size = 2, position = c("right", "bottom")) +
  tm_layout(legend.stack = FALSE,inner.margins = 0.19)+
  tm_layout(title = "Distribución Índice de Desarrollo Humano \n África")
```

### **Gráficos tmap regular, 2**

```{r message=FALSE, warning=FALSE}
tmap_mode("plot")

tm_shape(africa) +
tm_polygons("HDI", 
          palette = "RdYlBu")+
  tm_scale_bar(position=c("right", "bottom")) +
  tm_compass(size = 2, position=c("right", "bottom"))+
  tm_layout(inner.margins = 0.18)+
  tm_layout(title = "Distribución Índice de Desarrollo Humano \n África")
```


Row6 {data-width=200}
-----------------------------------------------------------------------

### **Gráfico con Cartography**

```{r}
plot(st_geometry(africa), col="darkseagreen3", border="darkseagreen4",  
     bg = "lightblue1", lwd = 0.5)

propSymbolsChoroLayer(
  x = africa, 
  var = "HDI", 
  inches = 0.1,
  border = "grey50",
  lwd = 1,
  legend.var.pos = "África", 
  legend.var.title.txt = "Índice Desarrollo Humano",
  var2 = "HDI",
  method = "equal", 
  nclass = 6, 
  col = carto.pal(pal1 = "sand.pal", n1 = 6),
  #legend.var2.values.rnd = -2,
  legend.var2.pos = "left", 
  legend.var2.title.txt = "HDI"
) 

# layout
layoutLayer(title="Índice de Desarrollo Humano África", 
            scale = 5, tabtitle = TRUE, frame = FALSE)
# north arrow
north(pos = "topleft")
```

# Gráfico con ggmap google

```{r}
Country <- "africa"
gc <- geocode('africa')
center <- as.numeric(gc) 

 africamap = ggmap(get_googlemap(center= center, zoom=3),extent="normal")
# plot(africamap)

Get_Map_africa <-
  get_map(
      location = center
    , zoom = 3
    , maptype = "roadmap"
    , messaging = FALSE
    , urlonly = FALSE
    , filename = "ggmapTemp"
    , crop = TRUE
    , color = "color"
    , source = "google"
    )
plot(Get_Map_africa)
class(Get_Map_africa)
```

```{r}
leaflet(data = africa) %>% 
  addPolygons(data = africa, fill = FALSE) %>% 
  addMiniMap()
```

